// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type PlatformGame struct {
	ID          uuid.UUID
	Title       string
	Description string
	Src         string
	Icon        string
	Created     time.Time
}

type PlatformGamePreview struct {
	GameID    uuid.UUID
	PreviewID uuid.UUID
}

type PlatformPreview struct {
	ID    uuid.UUID
	Image string
	Video *string
}

type PlatformUser struct {
	ID               uuid.UUID
	Name             string
	Email            string
	Password         string
	IsAdmin          bool
	VerificationCode string
	Verified         bool
	Birthday         *time.Time
	Gender           *string
	CreatedAt        time.Time
}
