// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID          uuid.UUID
	Title       string
	Description string
	Src         string
	Icon        string
	Created     pgtype.Timestamp
}

type GamePreview struct {
	GameID    uuid.UUID
	PreviewID uuid.UUID
}

type Preview struct {
	ID    uuid.UUID
	Image string
	Video *string
}
