FROM node:18-alpine AS builder
WORKDIR /app
COPY GamePlatformAdminPanel/my-app/package*.json ./
RUN npm install 
COPY GamePlatformAdminPanel/my-app .
RUN npm run build

FROM nginx:1.16.0-alpine
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY GamePlatformAdminPanel/my-app/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]