definitions:
  DTO.CreateGameInput:
    properties:
      description:
        type: string
      src:
        type: string
      title:
        type: string
    required:
    - description
    - src
    - title
    type: object
  DTO.ForgotPasswordInput:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  DTO.GameResponse:
    properties:
      description:
        type: string
      icon:
        type: string
      id:
        type: string
      previews:
        items:
          $ref: '#/definitions/DTO.PreviewResponse'
        type: array
      src:
        type: string
      title:
        type: string
    type: object
  DTO.GameResponseDTO:
    properties:
      game:
        $ref: '#/definitions/DTO.GameResponse'
    type: object
  DTO.GameResponseOnly:
    properties:
      description:
        type: string
      icon:
        type: string
      id:
        type: string
      src:
        type: string
      title:
        type: string
    type: object
  DTO.GameResponseOnlyDTO:
    properties:
      game:
        $ref: '#/definitions/DTO.GameResponseOnly'
    type: object
  DTO.GamesResponseDTO:
    properties:
      games:
        items:
          $ref: '#/definitions/DTO.GameResponseOnly'
        type: array
    type: object
  DTO.PreviewResponse:
    properties:
      id:
        type: string
      image:
        type: string
      video:
        type: string
    type: object
  DTO.PreviewResponseDTO:
    properties:
      preview:
        $ref: '#/definitions/DTO.PreviewResponse'
    type: object
  DTO.ResetPasswordInput:
    properties:
      password:
        type: string
      password_confirm:
        type: string
    required:
    - password
    - password_confirm
    type: object
  DTO.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  DTO.SignUpInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      password_confirm:
        type: string
    required:
    - email
    - name
    - password
    - password_confirm
    type: object
  DTO.TokenResponse:
    properties:
      access_token:
        type: string
      expired_in:
        type: string
    type: object
  DTO.UpdateGameInput:
    properties:
      description:
        type: string
      src:
        type: string
      title:
        type: string
    required:
    - description
    - src
    - title
    type: object
  DTO.UpdateUserInput:
    properties:
      birthday:
        type: string
      gender:
        type: string
      is_admin:
        type: boolean
      name:
        type: string
    type: object
  DTO.UserResponse:
    properties:
      birthday:
        type: string
      created_at:
        type: string
      email:
        type: string
      gender:
        type: string
      id:
        type: string
      is_admin:
        type: boolean
      name:
        type: string
    type: object
  DTO.UserResponseDTO:
    properties:
      user:
        $ref: '#/definitions/DTO.UserResponse'
    type: object
  DTO.UsersResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/DTO.UserResponse'
        type: array
    type: object
  api.Error:
    properties:
      code:
        type: string
      message:
        type: string
      parameter:
        type: string
    type: object
  api.ErrorResponse:
    properties:
      error:
        items:
          $ref: '#/definitions/api.Error'
        type: array
      status:
        type: string
    type: object
  api.Response:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_GameResponseDTO:
    properties:
      data:
        $ref: '#/definitions/DTO.GameResponseDTO'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_GameResponseOnlyDTO:
    properties:
      data:
        $ref: '#/definitions/DTO.GameResponseOnlyDTO'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_GamesResponseDTO:
    properties:
      data:
        $ref: '#/definitions/DTO.GamesResponseDTO'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_PreviewResponseDTO:
    properties:
      data:
        $ref: '#/definitions/DTO.PreviewResponseDTO'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_TokenResponse:
    properties:
      data:
        $ref: '#/definitions/DTO.TokenResponse'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_UserResponseDTO:
    properties:
      data:
        $ref: '#/definitions/DTO.UserResponseDTO'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_UsersResponse:
    properties:
      data:
        $ref: '#/definitions/DTO.UsersResponse'
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/forgot-password:
    post:
      consumes:
      - application/json
      description: forgot password
      parameters:
      - description: ForgotPasswordInput
        in: body
        name: ForgotPasswordInput
        required: true
        schema:
          $ref: '#/definitions/DTO.ForgotPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: User email is not verified
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: sign in user
      parameters:
      - description: SignInInput
        in: body
        name: SignInInput
        required: true
        schema:
          $ref: '#/definitions/DTO.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/logout:
    get:
      consumes:
      - application/json
      description: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: refresh access token
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_TokenResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: sign up user
      parameters:
      - description: SignUpInput
        in: body
        name: SignUpInput
        required: true
        schema:
          $ref: '#/definitions/DTO.SignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_UserResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/reset-password:
    patch:
      consumes:
      - application/json
      description: reset user password
      parameters:
      - description: reset code
        in: path
        name: reset_code
        required: true
        type: string
      - description: ResetPasswordInput
        in: body
        name: ResetPasswordInput
        required: true
        schema:
          $ref: '#/definitions/DTO.ResetPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/verify-email:
    post:
      description: verify user email
      parameters:
      - description: Verification code
        in: path
        name: verify_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/games:
    post:
      consumes:
      - application/json
      description: create game
      parameters:
      - description: CreateGameInput
        in: body
        name: CreateGameInput
        required: true
        schema:
          $ref: '#/definitions/DTO.CreateGameInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_GameResponseOnlyDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Game
  /api/v1/games/:
    get:
      description: get all game
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_GamesResponseDTO'
        "500":
          description: Internal Server Error
      tags:
      - Game
    post:
      description: create game preview
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_PreviewResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Game
  /api/v1/games/{id}:
    delete:
      description: delete game by id
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - Game
    get:
      description: get game by id
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_GameResponseDTO'
        "500":
          description: Internal Server Error
      tags:
      - Game
    patch:
      consumes:
      - application/json
      description: update game
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      - description: UpdateGameInput
        in: body
        name: UpdateGameInput
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdateGameInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - Game
  /api/v1/games/{id}/icon:
    post:
      consumes:
      - application/json
      description: upload game icon
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - Game
  /api/v1/games/preview/:
    delete:
      description: delete preview by id
      parameters:
      - description: Preview ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - Game
  /api/v1/users/:
    delete:
      description: delete user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - User
    get:
      description: get user by id
      parameters:
      - description: user id
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_UsersResponse'
        "500":
          description: Internal Server Error
      tags:
      - User
    patch:
      description: update another user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: UpdateUserInput
        in: body
        name: UpdateUserInput
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - User
  /api/v1/users/me:
    get:
      description: get current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_UserResponseDTO'
        "401":
          description: Unauthorized
      tags:
      - User
    patch:
      description: update user
      parameters:
      - description: UpdateUserInput
        in: body
        name: UpdateUserInput
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - User
swagger: "2.0"
